name: Validate Code
on:
  push:
    paths:
      - '**.java'
  workflow_dispatch:

jobs:
  validate_and_build:
    name: Validates and builds
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: x64
          
      - name: Clean
        run: mvn -ntp clean
      
      - name: Checkstyle check
        run: mvn -ntp checkstyle:check -Dcheckstyle.violationSeverity=warning
      
      - name: Build
        run: mvn -ntp compile
        
      - name: Main presenter tests
        run: mvn -ntp test -Dtest=MainPresenterTest